disabled_rules:
- trailing_whitespace

excluded:
- Carthage

file_length:
- 300
- 600

line_length: 180

type_body_length:
- 100 # warning
- 200 # error

identifier_name:
min_length:
warning: 1
error: 0
max_length:
warning: 60
error: 80
excluded:
- rl

function_body_length:
- 30 # warning
- 100 # error

#force_cast: warning
force_try: error
#force_unwrapping: error

private_outlet: error


